Fix #518 - Supprt null values in either sdpMid or sdpMLineIndex (but not both)
react-native-webrtc/react-native-webrtc pull request #1520
Opened 2024-03-14 21:19 UTC by omerts

I have tested this on Android, but not on iOS as I have no access to a mac.

2024-03-15 05:18 UTC, 8BallBomBom commented on android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
>                  promise.reject("E_TYPE_ERROR", "Invalid argument");
Might be a bit better to have a more specific error like everywhere else 🤔

2024-03-15 05:20 UTC, 8BallBomBom requested changes
Could you please run the provided code format script and submit the changes.
Looks good but will need testing.

2024-03-15 09:13 UTC, saghul commented
Can you check if the native code allows this in both platforms?

2024-03-16 22:15 UTC, 8BallBomBom commented
Haven't currently got any Apple devices but will try and run some tests shortly 👍🏻

2024-06-04 11:40 UTC, saghul approved these changes

2024-06-04 11:42 UTC, merged